In [1]:
# Import necessary libraries
import pandas as pd
import matplotlib

# Load CSV data
csv_file_path = 'December-2022-revised-110523-iii999.csv'  # Replace with the path to your CSV file
df = pd.read_csv(csv_file_path)

/tmp/ipykernel_25341/2385801315.py:3: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
/tmp/ipykernel_25341/2385801315.py:4: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html

In [2]:
pd.set_option('display.max_columns',30)

In [3]:
df.head()

,Period,Org Code,Parent Org,Org name,A&E attendances Type 1,A&E attendances Type 2,A&E attendances Other A&E Department,A&E attendances Booked Appointments Type 1,A&E attendances Booked Appointments Type 2,A&E attendances Booked Appointments Other Department,Attendances over 4hrs Type 1,Attendances over 4hrs Type 2,Attendances over 4hrs Other Department,Attendances over 4hrs Booked Appointments Type 1,Attendances over 4hrs Booked Appointments Type 2,Attendances over 4hrs Booked Appointments Other Department,Patients who have waited 4-12 hs from DTA to admission,Patients who have waited 12+ hrs from DTA to admission,Emergency admissions via A&E - Type 1,Emergency admissions via A&E - Type 2,Emergency admissions via A&E - Other A&E department,Other emergency admissions
0,MSitAE-DECEMBER-2022,AXG,NHS ENGLAND SOUTH WEST,WILTSHIRE HEALTH & CARE,0,0,1804,0,0,45,0,0,36,0,0,0,0,0,0,0,0,0
1,MSitAE-DECEMBER-2022,NDJ,NHS ENGLAND SOUTH EAST,FIRST COMMUNITY HEALTH AND CARE CIC,0,0,1903,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,MSitAE-DECEMBER-2022,NR3,NHS ENGLAND MIDLANDS,NOTTINGHAM CITYCARE PARTNERSHIP,0,0,5444,0,0,286,0,0,1568,0,0,0,0,0,0,0,0,0
3,MSitAE-DECEMBER-2022,RLQ,NHS ENGLAND MIDLANDS,WYE VALLEY NHS TRUST,5880,0,0,135,0,0,3300,0,0,52,0,0,90,346,1591,0,0,523
4,MSitAE-DECEMBER-2022,RWY,NHS ENGLAND NORTH EAST AND YORKSHIRE,CALDERDALE AND HUDDERSFIELD NHS FOUNDATION TRUST,15501,0,0,0,0,0,6148,0,0,0,0,0,1419,12,3391,0,0,944

In [4]:
df.sum()

Period                                                        MSitAE-DECEMBER-2022MSitAE-DECEMBER-2022MSitAE...
Org Code                                                      AXGNDJNR3RLQRWY8J094AAHC82038DD401L83087NL7NQT...
Parent Org                                                    NHS ENGLAND SOUTH WEST NHS ENGLAND SOUTH EAST ...
Org name                                                      WILTSHIRE HEALTH & CAREFIRST COMMUNITY HEALTH ...
A&E attendances Type 1                                                                                  2820454
A&E attendances Type 2                                                                                    72764
A&E attendances Other A&E Department                                                                    1549250
A&E attendances Booked Appointments Type 1                                                                54908
A&E attendances Booked Appointments Type 2                                                                  420
A&E attendances Booked Appointments Other Department                                                      90362
Attendances over 4hrs Type 1                                                                            1251660
Attendances over 4hrs Type 2                                                                               2104
Attendances over 4hrs Other Department                                                                   152124
Attendances over 4hrs Booked Appointments Type 1                                                          14892
Attendances over 4hrs Booked Appointments Type 2                                                             26
Attendances over 4hrs Booked Appointments Other Department                                                 2956
Patients who have waited 4-12 hs from DTA to admission                                                   231096
Patients who have waited 12+ hrs from DTA to admission                                                   109146
Emergency admissions via A&E - Type 1                                                                    756404
Emergency admissions via A&E - Type 2                                                                      2718
Emergency admissions via A&E - Other A&E department                                                       12342
Other emergency admissions                                                                               263424
dtype: object

In [5]:
print(df.dtypes)

Period                                                        object
Org Code                                                      object
Parent Org                                                    object
Org name                                                      object
A&E attendances Type 1                                         int64
A&E attendances Type 2                                         int64
A&E attendances Other A&E Department                           int64
A&E attendances Booked Appointments Type 1                     int64
A&E attendances Booked Appointments Type 2                     int64
A&E attendances Booked Appointments Other Department           int64
Attendances over 4hrs Type 1                                   int64
Attendances over 4hrs Type 2                                   int64
Attendances over 4hrs Other Department                         int64
Attendances over 4hrs Booked Appointments Type 1               int64
Attendances over 4hrs Booked Appointments Type 2               int64
Attendances over 4hrs Booked Appointments Other Department     int64
Patients who have waited 4-12 hs from DTA to admission         int64
Patients who have waited 12+ hrs from DTA to admission         int64
Emergency admissions via A&E - Type 1                          int64
Emergency admissions via A&E - Type 2                          int64
Emergency admissions via A&E - Other A&E department            int64
Other emergency admissions                                     int64
dtype: object

In [6]:
# Check for missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Period                                                        0
Org Code                                                      0
Parent Org                                                    0
Org name                                                      0
A&E attendances Type 1                                        0
A&E attendances Type 2                                        0
A&E attendances Other A&E Department                          0
A&E attendances Booked Appointments Type 1                    0
A&E attendances Booked Appointments Type 2                    0
A&E attendances Booked Appointments Other Department          0
Attendances over 4hrs Type 1                                  0
Attendances over 4hrs Type 2                                  0
Attendances over 4hrs Other Department                        0
Attendances over 4hrs Booked Appointments Type 1              0
Attendances over 4hrs Booked Appointments Type 2              0
Attendances over 4hrs Booked Appointments Other Department    0
Patients who have waited 4-12 hs from DTA to admission        0
Patients who have waited 12+ hrs from DTA to admission        0
Emergency admissions via A&E - Type 1                         0
Emergency admissions via A&E - Type 2                         0
Emergency admissions via A&E - Other A&E department           0
Other emergency admissions                                    0
dtype: int64

In [7]:
# Check for duplicate rows
duplicate_rows = df[df.duplicated()]
print("\nDuplicate rows:")
print(duplicate_rows)

Duplicate rows:
Empty DataFrame
Columns: [Period, Org Code, Parent Org, Org name, A&E attendances Type 1, A&E attendances Type 2, A&E attendances Other A&E Department, A&E attendances Booked Appointments Type 1, A&E attendances Booked Appointments Type 2, A&E attendances Booked Appointments Other Department, Attendances over 4hrs Type 1, Attendances over 4hrs Type 2, Attendances over 4hrs Other Department, Attendances over 4hrs Booked Appointments Type 1, Attendances over 4hrs Booked Appointments Type 2, Attendances over 4hrs Booked Appointments Other Department, Patients who have waited 4-12 hs from DTA to admission, Patients who have waited 12+ hrs from DTA to admission, Emergency admissions via A&E - Type 1, Emergency admissions via A&E - Type 2, Emergency admissions via A&E - Other A&E department, Other emergency admissions]
Index: []

In [8]:
dfType1 = df[df['A&E attendances Type 1'] != 0]

In [16]:
dfType1['Type 1 Proportion attendances over 4hrs'] = dfType1['Attendances over 4hrs Type 1']/dfType1['A&E attendances Type 1']

In [10]:
dfType1['Total Admissions'] = dfType1['Emergency admissions via A&E - Type 1'] + dfType1['Emergency admissions via A&E - Type 2'] + dfType1['Emergency admissions via A&E - Other A&E department']

/tmp/ipykernel_25341/146278090.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfType1['Total Admissions'] = dfType1['Emergency admissions via A&E - Type 1'] + dfType1['Emergency admissions via A&E - Type 2'] + dfType1['Emergency admissions via A&E - Other A&E department']

In [17]:
dfType1['Proportion waiting over 4hrs for admission'] = (dfType1['Patients who have waited 4-12 hs from DTA to admission'] + dfType1['Patients who have waited 12+ hrs from DTA to admission'])/dfType1['Total Admissions']
dfType1['Proportion waiting over 12hrs for admission'] = (dfType1['Patients who have waited 12+ hrs from DTA to admission'])/dfType1['Total Admissions']

In [18]:
dfType1.head()

,Period,Org Code,Parent Org,Org name,A&E attendances Type 1,A&E attendances Type 2,A&E attendances Other A&E Department,A&E attendances Booked Appointments Type 1,A&E attendances Booked Appointments Type 2,A&E attendances Booked Appointments Other Department,Attendances over 4hrs Type 1,Attendances over 4hrs Type 2,Attendances over 4hrs Other Department,Attendances over 4hrs Booked Appointments Type 1,Attendances over 4hrs Booked Appointments Type 2,Attendances over 4hrs Booked Appointments Other Department,Patients who have waited 4-12 hs from DTA to admission,Patients who have waited 12+ hrs from DTA to admission,Emergency admissions via A&E - Type 1,Emergency admissions via A&E - Type 2,Emergency admissions via A&E - Other A&E department,Other emergency admissions,Type 1 Proportion attendances over 4hrs,Total Admissions,Proportion waiting over 4hrs for admission,Proportion waiting over 12hrs for admission
3,MSitAE-DECEMBER-2022,RLQ,NHS ENGLAND MIDLANDS,WYE VALLEY NHS TRUST,5880,0,0,135,0,0,3300,0,0,52,0,0,90,346,1591,0,0,523,0.561224,1591,0.274041,0.217473
4,MSitAE-DECEMBER-2022,RWY,NHS ENGLAND NORTH EAST AND YORKSHIRE,CALDERDALE AND HUDDERSFIELD NHS FOUNDATION TRUST,15501,0,0,0,0,0,6148,0,0,0,0,0,1419,12,3391,0,0,944,0.396620,3391,0.421999,0.003539
13,MSitAE-DECEMBER-2022,RWA,NHS ENGLAND NORTH EAST AND YORKSHIRE,HULL UNIVERSITY TEACHING HOSPITALS NHS TRUST,10318,0,0,0,0,0,6227,0,0,0,0,0,979,631,3101,0,0,2303,0.603508,3101,0.519187,0.203483
25,MSitAE-DECEMBER-2022,RWE,NHS ENGLAND MIDLANDS,UNIVERSITY HOSPITALS OF LEICESTER NHS TRUST,21193,1464,0,0,0,0,11780,39,0,0,0,0,1580,1299,5145,4,0,3171,0.555844,5149,0.559138,0.252282
34,MSitAE-DECEMBER-2022,RA9,NHS ENGLAND SOUTH WEST,TORBAY AND SOUTH DEVON NHS FOUNDATION TRUST,5833,0,3180,249,0,0,4142,0,155,166,0,0,534,264,1744,0,0,1133,0.710098,1744,0.457569,0.151376

In [13]:
# Drop TOTAL row
dfType1 = dfType1[:-1]

In [19]:
dfType1[['Parent Org','Org name','A&E attendances Type 1','Total Admissions','Type 1 Proportion attendances over 4hrs','Proportion waiting over 4hrs for admission','Proportion waiting over 12hrs for admission']].to_csv('performance_metrics.csv')